use_frameworks!

platform :ios, '8.0'

target 'ZYSimpleAlert_Example' do
  pod 'ZYSimpleAlert', :path => '../'

  target 'ZYSimpleAlert_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
